### ISSUE TITLE
Local instance fails to start, code: 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by mdozmorov** [jkanche/kana#81]
Awesome app! `yarn` installation works but attempts to start it fail. Tried `npm run start` and `yarn start`. The error from the latter command:
```bash
Starting the development server...

/Users/som846993/Downloads/kana/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/som846993/Downloads/kana/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/som846993/Downloads/kana/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/som846993/Downloads/kana/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/som846993/Downloads/kana/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/som846993/Downloads/kana/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/som846993/Downloads/kana/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/som846993/Downloads/kana/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/som846993/Downloads/kana/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jkanche** [comment]
seems to be an issue with how node was setup on the machine - 

- https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
- https://github.com/facebook/create-react-app/issues/11708

**Comment by mdozmorov** [comment]
It helped, thanks, @jkanche! Of note, I created a separate Conda environment, the app works with `export NODE_OPTIONS=--openssl-legacy-provider`. It may be worth adding to README. Thanks again, impressive work!
